### ISSUE TITLE
[Bug]: 签名服务器异常

### ISSUE THREAD

**Issue by orangeZSCB** [LagrangeDev/go-cqhttp#22]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [x] 我已经仔细阅读上述教程和 ["提问前需知"](https://forums.go-cqhttp.org/t/topic/141)
- [x] 我已经使用 [dev分支版本](https://github.com/Mrs4s/go-cqhttp/actions/workflows/ci.yml) 测试过，问题依旧存在。
- [x] 我已经在 [Issue Tracker](https://github.com/Mrs4s/go-cqhttp/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [x] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### go-cqhttp 版本

6217b6b

### 运行环境

Windows (64)

### 运行架构

AMD64

### 连接方式

WebSocket (反向)

### 使用协议

0 | Default

### 重现步骤

运行此版本 go-cqhttp 扫码登陆报错，得到 all sign service down

### 期望的结果是什么？

签名服务器正常

### 实际的结果是什么？

得到 all sign service down 的报错
`[FATAL]: 登录时发生致命错误: all sign service down`

### 简单的复现代码/链接（可选）

```golang

```

### 日志记录（可选）

```golang
D:\maibot\orangebot\orangemaibot\gocq>gcq
[2025-02-12 23:22:41] [INFO]: 当前版本:v2.0.0-beta.3
[2025-02-12 23:22:41] [INFO]: 将使用 device.json 内的设备信息运行Bot.
[2025-02-12 23:22:41] [INFO]: Bot将在5秒后登录并开始信息处理, 按 Ctrl+C 取消.
[2025-02-12 23:22:46] [INFO]: 开始尝试登录并同步消息...
[2025-02-12 23:22:46] [INFO]: 使用协议: 3.2.15-30366
[2025-02-12 23:22:47] [INFO]: 正在检查协议更新...
[2025-02-12 23:22:49] [INFO]: Protocol -> connect to server: 111.30.187.227:8080
[2025-02-12 23:22:49] [FATAL]: 登录时发生致命错误: all sign service down
```

### 补充说明（可选）

今天我在初次使用此版本 go-cqhttp 时出现此报错。

我已经在 #9 中得知需要检查服务器连通性。我已经尝试过 ping 了 [https://github.com/LagrangeDev/Lagrange.Core/blob/9b17694773272fbd60e5362d8ed8af50ab23f181/Lagrange.Core/Utility/Sign/LinuxSigner.cs#L5](https://github.com/LagrangeDev/Lagrange.Core/blob/9b17694773272fbd60e5362d8ed8af50ab23f181/Lagrange.Core/Utility/Sign/LinuxSigner.cs#L5) 的服务器（ "https://sign.lagrangecore.org/api/sign/30366" ），开梯子和没开梯子的情况都试了一遍。得到的都是正常。网页直接访问得到的结果是：
```
Energy provided by Shiba riding a bicycle

Signatures calculated manually by university students

Currently, Shiba and the college student are in a stable mood
```

而运行得到的报错如日志记录所示。

**Comment by orangeZSCB** [comment]
我有尝试过将除 go-cqhttp 的本体文件除外的其他配置文件删去从头配置一遍，包括二维码登录和密码登录都试了一遍，运行的结果照旧。

**Comment by Redmomn** [comment]
不开梯子的情况下用无痕模式访问一下签名服务器，看能不能通
另外，配置文件最好贴一下，只要签名服务器部分就行

**Comment by orangeZSCB** [comment]
已经尝试过不开梯子无痕访问过签名服务器，正常。
这里的配置中。签名服务器直接是默认（"-"）
```
  # 数据包的签名服务器列表，第一个作为主签名服务器，后续作为备用
  # 与android签名不兼容
  # 示例:
  # sign-servers:
  #   - url: 'http://127.0.0.1:8080' # 本地签名服务器
  #   - url: 'https://signserver.example.com' # 线上签名服务器
  #   ...
  #
  # 服务器不提供自建
  sign-servers:
    - url: '-'  # 主签名服务器地址， 必填
    - url: '-'  # 备用
```
